# **EXPLORATORY DATA ANALYSIS**

## **Import Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

## **Connect to PostgreSQL and Load Dataset**

In [2]:
engine = create_engine('postgresql+psycopg2://olist_user:olist_password@localhost:5433/olist_db')

### **Bronze Layer**

In [3]:
df_cust = pd.read_sql(
    'SELECT * FROM bronze.customers', engine)
df_cust.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
df_loc = pd.read_sql(
    'SELECT * FROM bronze.geolocation', engine)
df_loc.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01037,-23.54562128115268,-46.63929204800168,sao paulo,SP
1,01046,-23.546081127035535,-46.64482029837157,sao paulo,SP
2,01046,-23.54612896641469,-46.64295148361138,sao paulo,SP
3,01041,-23.5443921648681,-46.63949930627844,sao paulo,SP
4,01035,-23.541577961711493,-46.64160722329613,sao paulo,SP

In [5]:
df_items = pd.read_sql(
    'SELECT * FROM bronze.order_items', engine)
df_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [6]:
df_payments = pd.read_sql(
    'SELECT * FROM bronze.order_payments', engine)
df_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [7]:
df_reviews = pd.read_sql(
    'SELECT * FROM bronze.order_reviews', engine)
df_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [8]:
df_orders = pd.read_sql(
    'SELECT * FROM bronze.orders', engine)
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [9]:
df_products = pd.read_sql(
    'SELECT * FROM bronze.products', engine)
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225,16,10,14
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000,30,18,20
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371,26,4,26
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625,20,17,13

In [10]:
df_sellers = pd.read_sql(
    'SELECT * FROM bronze.sellers', engine)
df_sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,04195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [11]:
df_product_trans = pd.read_sql(
    'SELECT * FROM bronze.category_translation', engine)
df_product_trans.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

### **Mart Layer**

In [12]:
mart_cust = pd.read_sql(
    'SELECT * FROM mart.customer_segmentation', engine)
mart_cust.head()

,customer_id,recency,frequency,monetary,r_score,f_score,m_score,rfm_score,customer_group,mart_created_at
0,08c5351a6aca1c1589a38f244edeee9d,730,1,72.89,1,5,3,153,Churned,2026-06-12 08:07:29.828597
1,683c54fc24d40ee9f8a6fc179fd9856c,729,1,59.50,1,5,2,152,Churned,2026-06-12 08:07:29.828597
2,86dc2ffce2dfff336de2f386a786e574,719,1,134.97,1,4,4,144,Uncategorized,2026-06-12 08:07:29.828597
3,b106b360fe2ef8849fbbd056f777b4d5,702,1,100.00,1,4,3,143,Uncategorized,2026-06-12 08:07:29.828597
4,b8cf418e97ae795672d326288dfab7a7,701,1,119.90,1,4,4,144,Uncategorized,2026-06-12 08:07:29.828597

In [13]:
mart_prod = pd.read_sql(
    'SELECT * FROM mart.product_performance', engine)
mart_prod .head()

,product_id,total_orders,total_units_sold,total_sales,avg_review_score,mart_created_at
0,00066f42aeeb9f3007548bb9d3f33c38,1,1,101.65,5.0,2026-06-12 08:07:29.833343
1,00088930e925c41fd95ebfe695fd2655,1,1,129.90,4.0,2026-06-12 08:07:29.833343
2,0009406fd7479715e4bef61dd91f2462,1,1,229.00,1.0,2026-06-12 08:07:29.833343
3,000b8f95fcb9e0096488278317764d19,2,2,117.80,5.0,2026-06-12 08:07:29.833343
4,000d9be29b5207b54e86aa1b1ac54872,1,1,199.00,5.0,2026-06-12 08:07:29.833343

In [14]:
mart_seller = pd.read_sql(
    'SELECT * FROM mart.seller_metrics', engine)
mart_seller.head()

,seller_id,total_orders,total_units_sold,total_sales,avg_review_score,late_delivery_rate,mart_created_at
0,0015a82c2db000af6aaaf3ae2ecb0532,3,3,2685.00,3.67,0.0,2026-06-12 08:07:29.832878
1,001cca7ae9ae17fb1caed9dfb1094831,200,239,25080.03,3.90,5.0,2026-06-12 08:07:29.832878
2,001e6ad469a905060d959994f1b41e4f,1,1,250.00,1.00,0.0,2026-06-12 08:07:29.832878
3,002100f778ceb8431b7a1020ff7ab48f,51,55,1234.50,3.98,16.0,2026-06-12 08:07:29.832878
4,003554e2dce176b5555353e4f3555ac8,1,1,120.00,5.00,0.0,2026-06-12 08:07:29.832878

In [15]:
mart_sales = pd.read_sql(
    'SELECT * FROM mart.monthly_sales', engine)
mart_sales.head()

,year,month,month_name,total_orders,total_customers,total_units_sold,total_sales,total_freight_value,avg_order_value,mom_sales_percentage,mart_created_at
0,2018,1,January,7220,7220,8208,950030.36,157271.53,131.58,27.71,2026-06-12 08:07:29.832909
1,2018,2,February,6694,6694,7672,844178.71,142730.25,126.11,-11.14,2026-06-12 08:07:29.832909
2,2018,3,March,7188,7188,8217,983213.44,171913.38,136.79,16.47,2026-06-12 08:07:29.832909
3,2018,4,April,6934,6934,7975,996647.75,163050.29,143.73,1.37,2026-06-12 08:07:29.832909
4,2018,5,May,6853,6853,7925,996517.68,153264.14,145.41,-0.01,2026-06-12 08:07:29.832909

## **Data Quality Check on Bronze Layer**

In [16]:
df_cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  str
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: str(5)
memory usage: 3.8 MB

In [17]:
df_loc.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  str
 1   geolocation_lat              1000163 non-null  str
 2   geolocation_lng              1000163 non-null  str
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: str(5)
memory usage: 38.2 MB

In [18]:
df_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  str
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  str
 6   freight_value        112650 non-null  str
dtypes: str(7)
memory usage: 6.0 MB

In [19]:
df_sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   str
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: str(4)
memory usage: 96.8 KB

In [20]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [21]:
# check missing values in "order_approved_at", "order_delivered_carrier_date", etc
df_orders[df_orders.isnull().any(axis=1)]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

In [22]:
# check order status for missing values in date columns
df_orders[df_orders.isnull().any(axis=1)].order_status.unique()

<StringArray>
[   'invoiced',     'shipped',  'processing', 'unavailable',    'canceled',
   'delivered',     'created',    'approved']
Length: 8, dtype: str

In [23]:
# check missing values with 'delivered' status
delivered_no_date = df_orders[(df_orders['order_delivered_customer_date'].isnull()) & 
                              (df_orders['order_status']=='delivered')]
print(f'Missing values in delivered customer date with delivered status : {len(delivered_no_date)}')

Missing values in delivered customer date with delivered status : 8

In [24]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  str
 3   product_description_lenght  32341 non-null  str
 4   product_photos_qty          32341 non-null  str
 5   product_weight_g            32949 non-null  str
 6   product_length_cm           32949 non-null  str
 7   product_height_cm           32949 non-null  str
 8   product_width_cm            32949 non-null  str
dtypes: str(9)
memory usage: 2.3 MB

In [25]:
# check missing values
df_products[df_products['product_category_name'].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650,17,14,12
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300,16,7,20
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200,20,20,20
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500,41,30,41
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300,35,7,12
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800,30,20,70
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800,30,10,23
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200,21,8,16
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300,45,16,45
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700,28,3,43

In [26]:
df_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  str
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: str(7)
memory usage: 5.3 MB

In [27]:
df_product_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

**INSIGHTS** :
1. Some tables (sellers, customers, category_transaltion, geolocation, order_items) do not have any missing values in all the columns
2. Order table has missing values in some date columns. These records with missing values in some date columns make sense since these records have incompleted order status. However, **eight records with "delivered" order status** have missing values in "order_delivered_customer_date" column. These records were retained in the pipeline and will result in NULL
3. A small number of missing values in product table is identified in other columns beside "product_id" column. Missing values in category column will be filled by "Uncategorized"
4. Order review table lacks lots of record in review_comment_title and review_comment_message.

## **Data Analysis**

### **Customer Segmentation**

In [28]:
# Customer segmentation
mart_cust.groupby('r_score')['recency'].describe().reset_index()

   r_score    count        mean        std    min    25%    50%    75%    max
0        1  19734.0  482.504105  62.427206  392.0  430.0  475.0  528.0  730.0
1        2  19733.0  325.805960  35.582097  277.0  291.0  323.0  357.0  392.0
2        3  19733.0  228.931232  26.722364  186.0  206.0  228.0  251.0  277.0
3        4  19733.0  143.983733  23.989433  102.0  123.0  143.0  166.0  186.0
4        5  19733.0   52.343334  26.254374    1.0   29.0   48.0   76.0  102.0

In [29]:
mart_cust.groupby('f_score')['frequency'].describe().reset_index()

   f_score    count  mean  std  min  25%  50%  75%  max
0        1  19734.0   1.0  0.0  1.0  1.0  1.0  1.0  1.0
1        2  19733.0   1.0  0.0  1.0  1.0  1.0  1.0  1.0
2        3  19733.0   1.0  0.0  1.0  1.0  1.0  1.0  1.0
3        4  19733.0   1.0  0.0  1.0  1.0  1.0  1.0  1.0
4        5  19733.0   1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [30]:
mart_cust.groupby('m_score')['monetary'].describe().reset_index()

,m_score,count,mean,std,min,25%,50%,75%,max
0,1,19734.0,25.120193,8.038677,0.85,19.0,25.0,30.0,39.00
1,2,19733.0,52.253757,7.768401,39.00,45.9,50.0,59.5,67.99
2,3,19733.0,86.131684,11.392447,67.99,76.7,86.9,98.0,107.00
3,4,19733.0,135.972409,18.977590,107.00,119.9,134.0,149.9,176.96
4,5,19733.0,389.298046,367.843870,176.96,205.0,269.9,399.9,13440.00

In [34]:
mart_cust.customer_group.value_counts().reset_index()

  customer_group  count
0        Churned  39549
1      Champions  19733
2      Potential  19654
3  Uncategorized  15844
4          Loyal   3886